services:
  nginx:
    image: nginx:alpine
    container_name: flux-payments-nginx
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - flux-network

  php:
    build: .
    container_name: flux-payments-app
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "9000"
    networks:
      - flux-network
  db:
    image: mariadb:10.11
    container_name: flux-payments-db
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - flux-network

volumes:
  db_data:

networks:
  flux-network:
    driver: bridge
